metric: "accuracy"
classification: true
data_path: "/data/#Representation_learning/age/data.csv"
index_column: "client_id"
time_column: "event_time"
target_column: "target"
categorical_columns: ["small_group"]
numerical_columns:  ["amount_rur"]
seq_len_limit: 1000 # params.train.max_seq_len
seq_len_trunc_type: "last"
split_sizes:
  test: 0.2
  train: 0.8
seed: 42
output_size: 
# Time format: day number from 2 year period. scaled to [0,1]