metric: auc
classification: true
data_path: "/home/dev/2023_03/Datasets/aevent_seq/datasets/data/physionet/PhysioNet/processed/data.csv"
index_column: "user"
time_column: "event_time"
target_column: "target"
categorical_columns: ["Gender", "ICUType", "MechVent"]
numerical_columns:  ['Age', 'Height', 'Weight', 'Albumin', 'ALP', 'ALT', 
                    'AST', 'Bilirubin', 'BUN', 'Cholesterol', 'Creatinine', 'DiasABP', 
                    'FiO2', 'GCS', 'Glucose', 'HCO3', 'HCT', 'HR', 'K', 'Lactate', 'Mg', 
                    'MAP', 'Na', 'NIDiasABP', 'NIMAP', 'NISysABP', 'PaCO2', 'PaO2', 'pH', 
                    'Platelets', 'RespRate', 'SaO2', 'SysABP', 'Temp', 'TroponinI', 'TroponinT', 
                    'Urine', 'WBC']
seq_len_limit: 200 # params.train.max_seq_len
seq_len_trunc_type: "last"
split_sizes:
  test: 0.2
  train: 0.8
seed: 42
output_size: 
# Time format: 0 to 1. (Orig: 0 to 48 hours)